global:
  scrape_interval: 60s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    target_groups:
      - targets:
          - localhost:9090

  - job_name: node
    target_groups:
      - targets:
          - localhost:9100

  - job_name: fake_exporter
    params:
      metrics: [1024]
      # fix the random seed to not spam prometheus with metrics
      seed: [0]
    file_sd_configs:
      - names:
          - fake_exporter.yml
